Repository sourcefuse/j-arc, pull requests merged in 2023-08, with the labels that each got.

#49 Fixes related to sandbox samples
  libs/core/src/main/java/com/sourcefuse/jarc/core/awares/AuditorAwareImpl.java
  libs/core/src/main/java/com/sourcefuse/jarc/core/constants/CommonConstants.java
  libs/jarc-auth-lib/src/main/java/com/sourcefuse/jarc/authlib/AuthLibApplication.java
  libs/jarc-auth-lib/src/main/java/com/sourcefuse/jarc/authlib/config/SecurityConfig.java
  libs/jarc-auth-lib/src/test/resources/application.properties
  services/audit-service/src/main/java/com/sourcefuse/jarc/services/auditservice/models/AuditLog.java
  services/audit-service/src/test/java/com/sourcefuse/jarc/services/auditservice/AuditControllerTests.java
  services/auth-service/src/main/java/com/sourcefuse/jarc/services/authservice/AuthServiceApplication.java
  services/auth-service/src/main/java/com/sourcefuse/jarc/services/authservice/config/SoftDeletesRepositoryConfig.java
  services/auth-service/src/main/java/com/sourcefuse/jarc/services/authservice/controller/KeycloakController.java
  services/auth-service/src/main/java/com/sourcefuse/jarc/services/authservice/models/AuthClient.java
  services/auth-service/src/main/java/com/sourcefuse/jarc/services/authservice/models/Role.java
  services/auth-service/src/main/java/com/sourcefuse/jarc/services/authservice/models/Tenant.java
  services/auth-service/src/main/java/com/sourcefuse/jarc/services/authservice/models/User.java
  services/auth-service/src/main/java/com/sourcefuse/jarc/services/authservice/models/UserTenant.java
  services/auth-service/src/main/java/com/sourcefuse/jarc/services/authservice/services/KeycloakAuthService.java
  services/auth-service/src/main/java/com/sourcefuse/jarc/services/authservice/specifications/AuthClientSpecification.java
  services/auth-service/src/main/resources/application.properties
  services/user-tenant-service/pom.xml
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/controller/GroupController.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/controller/RoleController.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/controller/RoleUserTenantController.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/controller/TenantController.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/controller/TenantUserController.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/controller/UserGroupController.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/controller/UserGroupsController.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/controller/UserTenantController.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/controller/UserTenantPrefsController.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/dto/User.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/dto/UserCredentials.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/dto/UserDto.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/dto/UserView.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/repository/UserCredentialRepository.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/service/TenantServiceImpl.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/service/TenantUserServiceImpl.java
  services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/specifications/UserCredentialsSpecification.java
  services/user-tenant-service/src/test/java/com/sourcefuse/jarc/services/usertenantservice/UserTenantServiceApplicationTests.java
  services/user-tenant-service/src/test/java/com/sourcefuse/jarc/services/usertenantservice/constant/TestConstants.java
  services/user-tenant-service/src/test/java/com/sourcefuse/jarc/services/usertenantservice/integration/TenantUserControllerTests.java
  services/user-tenant-service/src/test/java/com/sourcefuse/jarc/services/usertenantservice/mocks/MockCurrentUserSession.java
  services/user-tenant-service/src/test/java/com/sourcefuse/jarc/services/usertenantservice/mocks/MockTenantUser.java
  services/user-tenant-service/src/test/java/com/sourcefuse/jarc/services/usertenantservice/unit/TenantUserControllerUnitTests.java
Labels: enhancement

#50 Feature to enable CORS
  libs/jarc-auth-lib/src/main/java/com/sourcefuse/jarc/authlib/config/SecurityConfig.java
  libs/jarc-auth-lib/src/main/java/com/sourcefuse/jarc/authlib/cors/CorsConfig.java
  libs/jarc-auth-lib/src/main/java/com/sourcefuse/jarc/authlib/cors/CorsFilter.java
  libs/jarc-auth-lib/src/main/resources/META-INF/additional-spring-configuration-metadata.json
Labels: enhancement

#45 add readme for user tenant service
  services/user-tenant-service/README.md
Labels: documentation

#53 Fixes for datatype miss-match issue in filter
  libs/core/src/main/java/com/sourcefuse/jarc/core/filters/constants/OperationPredicates.java
  libs/core/src/main/java/com/sourcefuse/jarc/core/filters/services/QueryService.java
  libs/core/src/test/java/com/sourcefuse/jarc/core/QueryServiceTests.java
  libs/core/src/test/java/com/sourcefuse/jarc/core/test/models/User.java
Labels: bug, enhancement
